version: "3.8"

services:
  tomo:
    container_name: "tomo"
    build:
      context: "./tomo"
      dockerfile: ".Dockerfile"
    volumes:
      - type: volume
        source: tomoakemi
        target: /tomo

  akemi:
    container_name: "akemi"
    build:
      context: "./akemi"
      dockerfile: ".Dockerfile"
    ports:
      - "5173:5173"
    depends_on:
      - tomo
    volumes:
      - type: volume
        source: tomoakemi
        target: /akemi

volumes:
  tomoakemi: